spring.application.name=agendador-tarefas
spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db_agendador}
api.security.token.secret=${JWT_SECRET}

usuario.url=${USUARIO_URL:http://localhost:8080}
server.port=8081